name: CI

on:
  push:
    branches:
      - main
    pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake build-essential libsdl2-dev

      - name: Configure project
        run: cmake -B build -S .

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: ./build/tests